### ISSUE TITLE
Inputs inside disabled fieldsets are considered required.

### ISSUE THREAD

**Issue by danielbraun** [rails/jquery-ujs#455]
The `requiredInputSelector` applies to inputs inside disabled fieldsets as well, which prevents the form from being submitted.

The solution should be adjusting the selector to ignore disabled fieldsets.

**Comment by abuisman** [comment]
It seems to me that this issue is solved with the latest version in master. Could you confirm this @danielbraun?

**Comment by danielbraun** [comment]
It seems solved when checking with jsfiddle, but in my use case it still doesn't work. I'll keep checking.

**Comment by danielbraun** [comment]
Check out this fiddle: https://jsfiddle.net/aw51xa7o/
It still doesn't work.

Was the pull request correctly merged?
I can't see [this](https://github.com/rails/jquery-ujs/commit/86a8528d019c8752919052c6457ad7d8a8bf4841) commit in master.

**Comment by dirschn** [comment]
Hi all, is there any plan to get this closed? I see there was an attempt that ended up being closed but I couldn't see a reason for it. If no one is working on it I don't mind giving it a shot.

**Comment by dirschn** [comment]
@danielbraun I don't think this is completed, we're still running into an issue with this.
